/**
 * CAD document helpers for Zoo KCL models. Geometry evaluation runs in the
 * Zoo engine (browser WebRTC via @kittycad/lib, or ML APIs server-side).
 */
export {
  DEFAULT_KCL as DEFAULT_SCRIPT,
  DEFAULT_ASSEMBLY_KCL,
  DEFAULT_INSTRUCTIONS_MD,
  PRODUCT_ASSEMBLY_PATH,
  cadDoc,
  normalizeCadDoc,
  getActiveComponent,
  listComponentsByKind,
  setActiveComponent,
  assemblyDropTargetId,
  updateComponentContent,
  addCadComponent,
  addCadComponents,
  removeCadComponents,
  upsertPartScript,
  upsertPartScripts,
  upsertCadContent,
  slugifyCadName,
  cadAssetFormatFromName,
  cadAssetImportMode,
  isEngineCadAssetFormat,
  importAssetPath,
  kclForForeignImport,
  parseForeignImports,
  isForeignImportOnlyScript,
  parseKclModuleImports,
  partModuleAlias,
  displayNameFromCadPath,
  toZooKclPath,
  fromZooKclPath,
  meshPartProxyKcl,
  insertPartIntoAssembly,
  buildKclProject,
  addCadAsset,
  importMeshAsPart,
  type CadAssetImportMode,
  type CadDoc,
  type CadComponent,
  type CadComponentKind,
  type CadAsset,
  type CadAssetFormat,
  type KclProjectBuild,
} from "@foundry/cad";

export type CadView = "orbit" | "iso" | "front" | "top" | "right";
