/**
 * Collaborative CAD sources. Python/build123d evaluates on the server;
 * Three.js displays the resulting mesh. Legacy KCL sources remain preserved.
 */
export {
  DEFAULT_KCL as DEFAULT_SCRIPT,
  DEFAULT_ASSEMBLY_KCL,
  DEFAULT_INSTRUCTIONS_MD,
  PRODUCT_ASSEMBLY_PATH,
  cadDoc,
  normalizeCadDoc,
  getActiveComponent,
  isCadStarterComponent,
  selectCadComponentId,
  pickCadAssemblyPreview,
  listComponentsByKind,
  setActiveComponent,
  assemblyDropTargetId,
  updateComponentContent,
  addCadComponent,
  addCadComponents,
  removeCadComponents,
  upsertPartScript,
  upsertPartScripts,
  upsertCadContent,
  slugifyCadName,
  cadAssetFormatFromName,
  cadAssetImportMode,
  isEngineCadAssetFormat,
  importAssetPath,
  kclForForeignImport,
  parseForeignImports,
  isForeignImportOnlyScript,
  parseKclModuleImports,
  partModuleAlias,
  displayNameFromCadPath,
  toZooKclPath,
  fromZooKclPath,
  meshPartProxyKcl,
  insertPartIntoAssembly,
  buildKclProject,
  buildPythonProject,
  isPythonCadComponent,
  pythonCadDoc,
  upsertPythonPart,
  upsertPythonParts,
  addCadAsset,
  importMeshAsPart,
  type CadAssetImportMode,
  type CadDoc,
  type CadComponent,
  type CadComponentKind,
  type CadAsset,
  type CadAssetFormat,
  type KclProjectBuild,
} from "@foundry/cad";

export type CadView = "orbit" | "iso" | "front" | "top" | "right";
