/**
 * Fabrication output: Gerber RS-274X copper/outline layers and an Excellon
 * drill file — the set a board house needs to quote and build.
 *
 * Two decisions shape this writer:
 *
 * Pads are emitted as filled regions (G36/G37) rather than flashed apertures.
 * Gerber apertures cannot be rotated, so a rotated rectangular pad would need a
 * separate aperture per angle, and rotation is the common case on a real board.
 * A region carries its own outline, so one code path covers every angle.
 *
 * Board Y points down (SVG convention, matching the canvas) while Gerber Y
 * points up, so every coordinate is flipped through the board height on the way
 * out. Getting this wrong mirrors the board, which a fab will not catch.
 */

import {
  footprintDef,
  type PcbDoc,
  type PcbLayer,
  type PcbPadDef,
  type PcbFootprint,
  type PcbPoint,
} from "@/lib/pcb/doc";
import { padWorldPosition, polylineSegments } from "@/lib/pcb/geometry";

/** Gerber 3.6 fixed-point: millimetres scaled by 1e6. */
const SCALE = 1e6;

export type GeneratedFile = { name: string; contents: string };

function coord(mm: number): string {
  return String(Math.round(mm * SCALE));
}

/** Board millimetres -> Gerber, flipping Y so the output is not mirrored. */
function pt(doc: PcbDoc, xMm: number, yMm: number): string {
  return `X${coord(xMm)}Y${coord(doc.board.heightMm - yMm)}`;
}

function header(kind: string): string[] {
  return [
    `G04 ${kind} generated by FOUNDRY*`,
    "%FSLAX36Y36*%",
    "%MOMM*%",
    "%LPD*%",
  ];
}

/**
 * Pad outline in board coordinates, as a closed polygon. Ovals become a
 * stadium approximated by `ARC_STEPS` segments per cap — fine at fab
 * resolution and far simpler than emitting real Gerber arcs.
 */
const ARC_STEPS = 16;

function padPolygon(fp: PcbFootprint, pad: PcbPadDef): { xMm: number; yMm: number }[] {
  const centre = padWorldPosition(fp, pad);
  const theta = (fp.rotationDeg * Math.PI) / 180;
  const cos = Math.cos(theta);
  const sin = Math.sin(theta);
  // Local outline, then rotate into board space around the pad centre.
  const local: [number, number][] = [];

  if (pad.shape === "oval") {
    const r = Math.min(pad.wMm, pad.hMm) / 2;
    const spine = Math.max(0, (Math.max(pad.wMm, pad.hMm) - Math.min(pad.wMm, pad.hMm)) / 2);
    const horizontal = pad.wMm >= pad.hMm;
    const [sx, sy] = horizontal ? [spine, 0] : [0, spine];
    // Two semicircular caps joined by the straight flanks.
    for (let i = 0; i <= ARC_STEPS; i++) {
      const a = (Math.PI * i) / ARC_STEPS + (horizontal ? -Math.PI / 2 : 0);
      local.push([sx + r * Math.cos(a), sy + r * Math.sin(a)]);
    }
    for (let i = 0; i <= ARC_STEPS; i++) {
      const a = (Math.PI * i) / ARC_STEPS + (horizontal ? Math.PI / 2 : Math.PI);
      local.push([-sx + r * Math.cos(a), -sy + r * Math.sin(a)]);
    }
  } else {
    const hw = pad.wMm / 2;
    const hh = pad.hMm / 2;
    local.push([-hw, -hh], [hw, -hh], [hw, hh], [-hw, hh]);
  }

  return local.map(([lx, ly]) => ({
    xMm: centre.xMm + lx * cos - ly * sin,
    yMm: centre.yMm + lx * sin + ly * cos,
  }));
}

/** The copper layers a pad appears on. Through-hole pads reach both. */
function padOnLayer(fp: PcbFootprint, pad: PcbPadDef, layer: PcbLayer): boolean {
  if (pad.plated) return true;
  return (fp.side === "front" ? "F.Cu" : "B.Cu") === layer;
}

function region(doc: PcbDoc, polygon: { xMm: number; yMm: number }[]): string[] {
  if (polygon.length < 3) return [];
  const out = ["G36*"];
  out.push(`${pt(doc, polygon[0]!.xMm, polygon[0]!.yMm)}D02*`);
  for (const p of polygon.slice(1)) out.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
  out.push(`${pt(doc, polygon[0]!.xMm, polygon[0]!.yMm)}D01*`, "G37*");
  return out;
}

/** Grows a polygon outward from its centroid — a cheap offset for knockouts. */
function grow(polygon: PcbPoint[], byMm: number): PcbPoint[] {
  if (byMm <= 0) return polygon;
  const cx = polygon.reduce((s, p) => s + p.xMm, 0) / polygon.length;
  const cy = polygon.reduce((s, p) => s + p.yMm, 0) / polygon.length;
  return polygon.map((p) => {
    const dx = p.xMm - cx;
    const dy = p.yMm - cy;
    const len = Math.hypot(dx, dy) || 1;
    return { xMm: p.xMm + (dx / len) * byMm, yMm: p.yMm + (dy / len) * byMm };
  });
}

/** A rectangle around a segment, used to knock a track out of a pour. */
function segmentBox(
  ax: number, ay: number, bx: number, by: number, halfWidth: number,
): PcbPoint[] {
  const dx = bx - ax;
  const dy = by - ay;
  const len = Math.hypot(dx, dy) || 1;
  // Unit normal, scaled to the half width.
  const nx = (-dy / len) * halfWidth;
  const ny = (dx / len) * halfWidth;
  // Extend the ends by the same amount so corners and stubs are covered.
  const ex = (dx / len) * halfWidth;
  const ey = (dy / len) * halfWidth;
  return [
    { xMm: ax - ex + nx, yMm: ay - ey + ny },
    { xMm: bx + ex + nx, yMm: by + ey + ny },
    { xMm: bx + ex - nx, yMm: by + ey - ny },
    { xMm: ax - ex - nx, yMm: ay - ey - ny },
  ];
}

/**
 * Copper pours for one layer, as a dark region followed by clear-polarity
 * knockouts for every foreign-net feature.
 *
 * Gerber applies polarity in stream order, so `%LPC*%` regions after the pour
 * cut holes in it — which is why the filled shape never has to be computed as a
 * polygon difference. Emitted before tracks and pads so those stay dark.
 */
function zoneFills(doc: PcbDoc, layer: PcbLayer, padNets: Map<string, string>): string[] {
  const lines: string[] = [];

  for (const zone of doc.zones) {
    if (zone.layer !== layer) continue;
    const clearance = zone.clearanceMm ?? doc.rules.clearanceMm;

    lines.push("%LPD*%", ...region(doc, zone.points));
    lines.push("%LPC*%");

    for (const track of doc.tracks) {
      if (track.layer !== layer || (zone.net && track.net === zone.net)) continue;
      for (const [ax, ay, bx, by] of polylineSegments(track.points)) {
        lines.push(...region(doc, segmentBox(ax, ay, bx, by, track.widthMm / 2 + clearance)));
      }
    }

    for (const via of doc.vias) {
      if (zone.net && via.net === zone.net) continue;
      lines.push(...region(doc, circlePolygon(via.xMm, via.yMm, via.diameterMm / 2 + clearance)));
    }

    for (const fp of doc.footprints) {
      const def = footprintDef(fp.libraryId);
      if (!def) continue;
      for (const pad of def.pads) {
        if (!padOnLayer(fp, pad, layer)) continue;
        const net = padNets.get(`${fp.id}:${pad.pin}`);
        if (zone.net && net === zone.net) continue;
        lines.push(...region(doc, grow(padPolygon(fp, pad), clearance)));
      }
    }

    lines.push("%LPD*%");
  }

  return lines;
}

function circlePolygon(cx: number, cy: number, r: number): PcbPoint[] {
  return Array.from({ length: ARC_STEPS * 2 }, (_, i) => {
    const a = (2 * Math.PI * i) / (ARC_STEPS * 2);
    return { xMm: cx + r * Math.cos(a), yMm: cy + r * Math.sin(a) };
  });
}

/** One copper layer: pours first, then tracks as strokes and pads as regions. */
export function gerberCopper(
  doc: PcbDoc,
  layer: PcbLayer,
  /** Pad net names keyed `${footprintId}:${pin}`; only pours need them. */
  padNets: Map<string, string> = new Map(),
): string {
  const lines = header(`${layer} copper`);
  lines.push(...zoneFills(doc, layer, padNets));

  // One circular aperture per distinct track width.
  const widths = [...new Set(doc.tracks.filter((t) => t.layer === layer).map((t) => t.widthMm))];
  const apertureFor = new Map<number, string>();
  widths.forEach((w, i) => {
    const code = `D${10 + i}`;
    apertureFor.set(w, code);
    lines.push(`%AD${code}C,${w.toFixed(6)}*%`);
  });
  // Vias need a round aperture too; give them their own codes.
  const viaDiameters = [...new Set(doc.vias.map((v) => v.diameterMm))];
  const viaAperture = new Map<number, string>();
  viaDiameters.forEach((d, i) => {
    const code = `D${10 + widths.length + i}`;
    viaAperture.set(d, code);
    lines.push(`%AD${code}C,${d.toFixed(6)}*%`);
  });

  for (const track of doc.tracks) {
    if (track.layer !== layer) continue;
    const code = apertureFor.get(track.widthMm);
    if (!code) continue;
    lines.push(`${code}*`);
    const [first, ...rest] = track.points;
    if (!first) continue;
    lines.push(`${pt(doc, first.xMm, first.yMm)}D02*`);
    for (const p of rest) lines.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
  }

  // Via annular rings are flashed on both copper layers.
  for (const via of doc.vias) {
    const code = viaAperture.get(via.diameterMm);
    if (!code) continue;
    lines.push(`${code}*`, `${pt(doc, via.xMm, via.yMm)}D03*`);
  }

  for (const fp of doc.footprints) {
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    for (const pad of def.pads) {
      if (!padOnLayer(fp, pad, layer)) continue;
      lines.push(...region(doc, padPolygon(fp, pad)));
    }
  }

  lines.push("M02*");
  return lines.join("\n") + "\n";
}

/** Edge.Cuts: the board outline, with rounded corners when the board has them. */
export function gerberOutline(doc: PcbDoc): string {
  const lines = header("Edge.Cuts outline");
  lines.push("%ADD10C,0.100000*%", "D10*");

  const { widthMm: w, heightMm: h } = doc.board;
  const r = Math.max(0, Math.min(doc.board.cornerRadiusMm, Math.min(w, h) / 2));

  const path: { xMm: number; yMm: number }[] = [];
  if (r <= 0) {
    path.push({ xMm: 0, yMm: 0 }, { xMm: w, yMm: 0 }, { xMm: w, yMm: h }, { xMm: 0, yMm: h });
  } else {
    // Corner arcs approximated by segments, matching the region approach.
    const corners: [number, number, number][] = [
      [r, r, 180],
      [w - r, r, 270],
      [w - r, h - r, 0],
      [r, h - r, 90],
    ];
    for (const [cx, cy, start] of corners) {
      for (let i = 0; i <= ARC_STEPS / 2; i++) {
        const a = ((start + (90 * i) / (ARC_STEPS / 2)) * Math.PI) / 180;
        path.push({ xMm: cx + r * Math.cos(a), yMm: cy + r * Math.sin(a) });
      }
    }
  }

  lines.push(`${pt(doc, path[0]!.xMm, path[0]!.yMm)}D02*`);
  for (const p of path.slice(1)) lines.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
  lines.push(`${pt(doc, path[0]!.xMm, path[0]!.yMm)}D01*`, "M02*");
  return lines.join("\n") + "\n";
}

/** Silkscreen: reference designators as outlines around each front-side body. */
export function gerberSilk(doc: PcbDoc): string {
  const lines = header("F.SilkS");
  lines.push("%ADD10C,0.150000*%", "D10*");

  for (const fp of doc.footprints) {
    if (fp.side !== "front") continue;
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    const theta = (fp.rotationDeg * Math.PI) / 180;
    const cos = Math.cos(theta);
    const sin = Math.sin(theta);
    const hw = def.bodyWMm / 2;
    const hh = def.bodyHMm / 2;
    const corners: [number, number][] = [
      [-hw, -hh],
      [hw, -hh],
      [hw, hh],
      [-hw, hh],
    ];
    const world = corners.map(([lx, ly]) => ({
      xMm: fp.xMm + lx * cos - ly * sin,
      yMm: fp.yMm + lx * sin + ly * cos,
    }));
    lines.push(`${pt(doc, world[0]!.xMm, world[0]!.yMm)}D02*`);
    for (const p of world.slice(1)) lines.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
    lines.push(`${pt(doc, world[0]!.xMm, world[0]!.yMm)}D01*`);
  }

  lines.push("M02*");
  return lines.join("\n") + "\n";
}

/**
 * Solder mask: an opening over every pad, grown by `expansionMm` so a small
 * registration error still leaves the whole pad exposed. Mask layers are drawn
 * as the openings themselves — the fab inverts them.
 */
export function gerberMask(doc: PcbDoc, layer: PcbLayer, expansionMm = 0.05): string {
  const lines = header(`${layer === "F.Cu" ? "F.Mask" : "B.Mask"} solder mask`);

  for (const fp of doc.footprints) {
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    for (const pad of def.pads) {
      if (!padOnLayer(fp, pad, layer)) continue;
      // Mechanical pads carry no net and need no opening.
      if (!pad.pin) continue;
      lines.push(...region(doc, grow(padPolygon(fp, pad), expansionMm)));
    }
  }

  // Vias are normally tented, so they get no mask opening.
  lines.push("M02*");
  return lines.join("\n") + "\n";
}

/**
 * Solder paste: stencil apertures for SMD pads only. Through-hole pads are
 * soldered, not paste-printed, so including them would ruin the stencil.
 */
export function gerberPaste(doc: PcbDoc, layer: PcbLayer): string {
  const lines = header(`${layer === "F.Cu" ? "F.Paste" : "B.Paste"} solder paste`);

  for (const fp of doc.footprints) {
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    for (const pad of def.pads) {
      if (pad.plated || !pad.pin) continue;
      if ((fp.side === "front" ? "F.Cu" : "B.Cu") !== layer) continue;
      lines.push(...region(doc, padPolygon(fp, pad)));
    }
  }

  lines.push("M02*");
  return lines.join("\n") + "\n";
}

/**
 * Excellon drill file. Plated holes only — vias plus any footprint pad marked
 * `plated`, which is how through-hole pads are flagged in the library.
 */
export function excellonDrill(doc: PcbDoc): string {
  const holes: { xMm: number; yMm: number; drillMm: number }[] = [];

  for (const via of doc.vias) {
    holes.push({ xMm: via.xMm, yMm: via.yMm, drillMm: via.drillMm });
  }
  for (const fp of doc.footprints) {
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    for (const pad of def.pads) {
      if (!pad.plated) continue;
      const at = padWorldPosition(fp, pad);
      // A through-hole pad's drill is the smaller pad dimension less the ring.
      const drillMm = Math.max(0.1, Math.min(pad.wMm, pad.hMm) - 0.4);
      holes.push({ xMm: at.xMm, yMm: at.yMm, drillMm });
    }
  }

  const sizes = [...new Set(holes.map((h) => Number(h.drillMm.toFixed(3))))].sort((a, b) => a - b);
  const lines = ["M48", "; Generated by FOUNDRY", "FMAT,2", "METRIC,TZ"];
  sizes.forEach((size, i) => lines.push(`T${i + 1}C${size.toFixed(3)}`));
  lines.push("%");

  sizes.forEach((size, i) => {
    lines.push(`T${i + 1}`);
    for (const hole of holes) {
      if (Number(hole.drillMm.toFixed(3)) !== size) continue;
      // Excellon shares the Gerber convention of Y up.
      lines.push(`X${hole.xMm.toFixed(3)}Y${(doc.board.heightMm - hole.yMm).toFixed(3)}`);
    }
  });

  lines.push("T0", "M30");
  return lines.join("\n") + "\n";
}

/**
 * The full fabrication set, ready to zip and send to a board house: both copper
 * layers, both mask layers, paste, silkscreen, outline and drill. Anything less
 * than mask + outline + drill gets a quote rejected.
 */
export function fabricationFiles(
  doc: PcbDoc,
  baseName = "board",
  padNets: Map<string, string> = new Map(),
): GeneratedFile[] {
  return [
    { name: `${baseName}-F_Cu.gbr`, contents: gerberCopper(doc, "F.Cu", padNets) },
    { name: `${baseName}-B_Cu.gbr`, contents: gerberCopper(doc, "B.Cu", padNets) },
    { name: `${baseName}-F_Mask.gbr`, contents: gerberMask(doc, "F.Cu") },
    { name: `${baseName}-B_Mask.gbr`, contents: gerberMask(doc, "B.Cu") },
    { name: `${baseName}-F_Paste.gbr`, contents: gerberPaste(doc, "F.Cu") },
    { name: `${baseName}-F_SilkS.gbr`, contents: gerberSilk(doc) },
    { name: `${baseName}-Edge_Cuts.gbr`, contents: gerberOutline(doc) },
    { name: `${baseName}.drl`, contents: excellonDrill(doc) },
  ];
}
