/**
 * Fabrication output: Gerber RS-274X copper/outline layers and an Excellon
 * drill file — the set a board house needs to quote and build.
 *
 * Two decisions shape this writer:
 *
 * Pads are emitted as filled regions (G36/G37) rather than flashed apertures.
 * Gerber apertures cannot be rotated, so a rotated rectangular pad would need a
 * separate aperture per angle, and rotation is the common case on a real board.
 * A region carries its own outline, so one code path covers every angle.
 *
 * Board Y points down (SVG convention, matching the canvas) while Gerber Y
 * points up, so every coordinate is flipped through the board height on the way
 * out. Getting this wrong mirrors the board, which a fab will not catch.
 */

import {
  footprintDef,
  type PcbDoc,
  type PcbLayer,
  type PcbPadDef,
  type PcbFootprint,
} from "@/lib/pcb/doc";
import { padWorldPosition } from "@/lib/pcb/geometry";

/** Gerber 3.6 fixed-point: millimetres scaled by 1e6. */
const SCALE = 1e6;

export type GeneratedFile = { name: string; contents: string };

function coord(mm: number): string {
  return String(Math.round(mm * SCALE));
}

/** Board millimetres -> Gerber, flipping Y so the output is not mirrored. */
function pt(doc: PcbDoc, xMm: number, yMm: number): string {
  return `X${coord(xMm)}Y${coord(doc.board.heightMm - yMm)}`;
}

function header(kind: string): string[] {
  return [
    `G04 ${kind} generated by FOUNDRY*`,
    "%FSLAX36Y36*%",
    "%MOMM*%",
    "%LPD*%",
  ];
}

/**
 * Pad outline in board coordinates, as a closed polygon. Ovals become a
 * stadium approximated by `ARC_STEPS` segments per cap — fine at fab
 * resolution and far simpler than emitting real Gerber arcs.
 */
const ARC_STEPS = 16;

function padPolygon(fp: PcbFootprint, pad: PcbPadDef): { xMm: number; yMm: number }[] {
  const centre = padWorldPosition(fp, pad);
  const theta = (fp.rotationDeg * Math.PI) / 180;
  const cos = Math.cos(theta);
  const sin = Math.sin(theta);
  // Local outline, then rotate into board space around the pad centre.
  const local: [number, number][] = [];

  if (pad.shape === "oval") {
    const r = Math.min(pad.wMm, pad.hMm) / 2;
    const spine = Math.max(0, (Math.max(pad.wMm, pad.hMm) - Math.min(pad.wMm, pad.hMm)) / 2);
    const horizontal = pad.wMm >= pad.hMm;
    const [sx, sy] = horizontal ? [spine, 0] : [0, spine];
    // Two semicircular caps joined by the straight flanks.
    for (let i = 0; i <= ARC_STEPS; i++) {
      const a = (Math.PI * i) / ARC_STEPS + (horizontal ? -Math.PI / 2 : 0);
      local.push([sx + r * Math.cos(a), sy + r * Math.sin(a)]);
    }
    for (let i = 0; i <= ARC_STEPS; i++) {
      const a = (Math.PI * i) / ARC_STEPS + (horizontal ? Math.PI / 2 : Math.PI);
      local.push([-sx + r * Math.cos(a), -sy + r * Math.sin(a)]);
    }
  } else {
    const hw = pad.wMm / 2;
    const hh = pad.hMm / 2;
    local.push([-hw, -hh], [hw, -hh], [hw, hh], [-hw, hh]);
  }

  return local.map(([lx, ly]) => ({
    xMm: centre.xMm + lx * cos - ly * sin,
    yMm: centre.yMm + lx * sin + ly * cos,
  }));
}

/** The copper layers a pad appears on. Through-hole pads reach both. */
function padOnLayer(fp: PcbFootprint, pad: PcbPadDef, layer: PcbLayer): boolean {
  if (pad.plated) return true;
  return (fp.side === "front" ? "F.Cu" : "B.Cu") === layer;
}

function region(doc: PcbDoc, polygon: { xMm: number; yMm: number }[]): string[] {
  if (polygon.length < 3) return [];
  const out = ["G36*"];
  out.push(`${pt(doc, polygon[0]!.xMm, polygon[0]!.yMm)}D02*`);
  for (const p of polygon.slice(1)) out.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
  out.push(`${pt(doc, polygon[0]!.xMm, polygon[0]!.yMm)}D01*`, "G37*");
  return out;
}

/** One copper layer: tracks as stroked polylines, pads as filled regions. */
export function gerberCopper(doc: PcbDoc, layer: PcbLayer): string {
  const lines = header(`${layer} copper`);

  // One circular aperture per distinct track width.
  const widths = [...new Set(doc.tracks.filter((t) => t.layer === layer).map((t) => t.widthMm))];
  const apertureFor = new Map<number, string>();
  widths.forEach((w, i) => {
    const code = `D${10 + i}`;
    apertureFor.set(w, code);
    lines.push(`%AD${code}C,${w.toFixed(6)}*%`);
  });
  // Vias need a round aperture too; give them their own codes.
  const viaDiameters = [...new Set(doc.vias.map((v) => v.diameterMm))];
  const viaAperture = new Map<number, string>();
  viaDiameters.forEach((d, i) => {
    const code = `D${10 + widths.length + i}`;
    viaAperture.set(d, code);
    lines.push(`%AD${code}C,${d.toFixed(6)}*%`);
  });

  for (const track of doc.tracks) {
    if (track.layer !== layer) continue;
    const code = apertureFor.get(track.widthMm);
    if (!code) continue;
    lines.push(`${code}*`);
    const [first, ...rest] = track.points;
    if (!first) continue;
    lines.push(`${pt(doc, first.xMm, first.yMm)}D02*`);
    for (const p of rest) lines.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
  }

  // Via annular rings are flashed on both copper layers.
  for (const via of doc.vias) {
    const code = viaAperture.get(via.diameterMm);
    if (!code) continue;
    lines.push(`${code}*`, `${pt(doc, via.xMm, via.yMm)}D03*`);
  }

  for (const fp of doc.footprints) {
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    for (const pad of def.pads) {
      if (!padOnLayer(fp, pad, layer)) continue;
      lines.push(...region(doc, padPolygon(fp, pad)));
    }
  }

  lines.push("M02*");
  return lines.join("\n") + "\n";
}

/** Edge.Cuts: the board outline, with rounded corners when the board has them. */
export function gerberOutline(doc: PcbDoc): string {
  const lines = header("Edge.Cuts outline");
  lines.push("%ADD10C,0.100000*%", "D10*");

  const { widthMm: w, heightMm: h } = doc.board;
  const r = Math.max(0, Math.min(doc.board.cornerRadiusMm, Math.min(w, h) / 2));

  const path: { xMm: number; yMm: number }[] = [];
  if (r <= 0) {
    path.push({ xMm: 0, yMm: 0 }, { xMm: w, yMm: 0 }, { xMm: w, yMm: h }, { xMm: 0, yMm: h });
  } else {
    // Corner arcs approximated by segments, matching the region approach.
    const corners: [number, number, number][] = [
      [r, r, 180],
      [w - r, r, 270],
      [w - r, h - r, 0],
      [r, h - r, 90],
    ];
    for (const [cx, cy, start] of corners) {
      for (let i = 0; i <= ARC_STEPS / 2; i++) {
        const a = ((start + (90 * i) / (ARC_STEPS / 2)) * Math.PI) / 180;
        path.push({ xMm: cx + r * Math.cos(a), yMm: cy + r * Math.sin(a) });
      }
    }
  }

  lines.push(`${pt(doc, path[0]!.xMm, path[0]!.yMm)}D02*`);
  for (const p of path.slice(1)) lines.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
  lines.push(`${pt(doc, path[0]!.xMm, path[0]!.yMm)}D01*`, "M02*");
  return lines.join("\n") + "\n";
}

/** Silkscreen: reference designators as outlines around each front-side body. */
export function gerberSilk(doc: PcbDoc): string {
  const lines = header("F.SilkS");
  lines.push("%ADD10C,0.150000*%", "D10*");

  for (const fp of doc.footprints) {
    if (fp.side !== "front") continue;
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    const theta = (fp.rotationDeg * Math.PI) / 180;
    const cos = Math.cos(theta);
    const sin = Math.sin(theta);
    const hw = def.bodyWMm / 2;
    const hh = def.bodyHMm / 2;
    const corners: [number, number][] = [
      [-hw, -hh],
      [hw, -hh],
      [hw, hh],
      [-hw, hh],
    ];
    const world = corners.map(([lx, ly]) => ({
      xMm: fp.xMm + lx * cos - ly * sin,
      yMm: fp.yMm + lx * sin + ly * cos,
    }));
    lines.push(`${pt(doc, world[0]!.xMm, world[0]!.yMm)}D02*`);
    for (const p of world.slice(1)) lines.push(`${pt(doc, p.xMm, p.yMm)}D01*`);
    lines.push(`${pt(doc, world[0]!.xMm, world[0]!.yMm)}D01*`);
  }

  lines.push("M02*");
  return lines.join("\n") + "\n";
}

/**
 * Excellon drill file. Plated holes only — vias plus any footprint pad marked
 * `plated`, which is how through-hole pads are flagged in the library.
 */
export function excellonDrill(doc: PcbDoc): string {
  const holes: { xMm: number; yMm: number; drillMm: number }[] = [];

  for (const via of doc.vias) {
    holes.push({ xMm: via.xMm, yMm: via.yMm, drillMm: via.drillMm });
  }
  for (const fp of doc.footprints) {
    const def = footprintDef(fp.libraryId);
    if (!def) continue;
    for (const pad of def.pads) {
      if (!pad.plated) continue;
      const at = padWorldPosition(fp, pad);
      // A through-hole pad's drill is the smaller pad dimension less the ring.
      const drillMm = Math.max(0.1, Math.min(pad.wMm, pad.hMm) - 0.4);
      holes.push({ xMm: at.xMm, yMm: at.yMm, drillMm });
    }
  }

  const sizes = [...new Set(holes.map((h) => Number(h.drillMm.toFixed(3))))].sort((a, b) => a - b);
  const lines = ["M48", "; Generated by FOUNDRY", "FMAT,2", "METRIC,TZ"];
  sizes.forEach((size, i) => lines.push(`T${i + 1}C${size.toFixed(3)}`));
  lines.push("%");

  sizes.forEach((size, i) => {
    lines.push(`T${i + 1}`);
    for (const hole of holes) {
      if (Number(hole.drillMm.toFixed(3)) !== size) continue;
      // Excellon shares the Gerber convention of Y up.
      lines.push(`X${hole.xMm.toFixed(3)}Y${(doc.board.heightMm - hole.yMm).toFixed(3)}`);
    }
  });

  lines.push("T0", "M30");
  return lines.join("\n") + "\n";
}

/** The full fabrication set, ready to zip and send to a board house. */
export function fabricationFiles(doc: PcbDoc, baseName = "board"): GeneratedFile[] {
  return [
    { name: `${baseName}-F_Cu.gbr`, contents: gerberCopper(doc, "F.Cu") },
    { name: `${baseName}-B_Cu.gbr`, contents: gerberCopper(doc, "B.Cu") },
    { name: `${baseName}-Edge_Cuts.gbr`, contents: gerberOutline(doc) },
    { name: `${baseName}-F_SilkS.gbr`, contents: gerberSilk(doc) },
    { name: `${baseName}.drl`, contents: excellonDrill(doc) },
  ];
}
