// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/sign-in" | "/auth/sign-up" | "/invite/[token]" | "/render/circuit" | "/render/model3d" | "/w/[workspaceSlug]" | "/w/[workspaceSlug]/projects/[projectSlug]/[stage]" | "/w/[workspaceSlug]/projects/[projectSlug]/overview" | "/w/[workspaceSlug]/settings" | "/workspaces"
type AppRouteHandlerRoutes = "/api/ai/chat" | "/api/auth/sign-in" | "/api/auth/sign-out" | "/api/auth/sign-up" | "/api/files/[...path]" | "/api/trpc/[trpc]"
type PageRoutes = never
type LayoutRoutes = "/" | "/w/[workspaceSlug]/projects/[projectSlug]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/chat": {}
  "/api/auth/sign-in": {}
  "/api/auth/sign-out": {}
  "/api/auth/sign-up": {}
  "/api/files/[...path]": { "path": string[]; }
  "/api/trpc/[trpc]": { "trpc": string; }
  "/auth/sign-in": {}
  "/auth/sign-up": {}
  "/invite/[token]": { "token": string; }
  "/render/circuit": {}
  "/render/model3d": {}
  "/w/[workspaceSlug]": { "workspaceSlug": string; }
  "/w/[workspaceSlug]/projects/[projectSlug]": { "workspaceSlug": string; "projectSlug": string; }
  "/w/[workspaceSlug]/projects/[projectSlug]/[stage]": { "workspaceSlug": string; "projectSlug": string; "stage": string; }
  "/w/[workspaceSlug]/projects/[projectSlug]/overview": { "workspaceSlug": string; "projectSlug": string; }
  "/w/[workspaceSlug]/settings": { "workspaceSlug": string; }
  "/workspaces": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/w/[workspaceSlug]/projects/[projectSlug]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
