// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../app/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-up">> = Specific
  const handler = {} as typeof import("../../app/auth/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/render/circuit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/render/circuit">> = Specific
  const handler = {} as typeof import("../../app/render/circuit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/render/model3d/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/render/model3d">> = Specific
  const handler = {} as typeof import("../../app/render/model3d/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[workspaceSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceSlug]">> = Specific
  const handler = {} as typeof import("../../app/w/[workspaceSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[workspaceSlug]/projects/[projectSlug]/[stage]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceSlug]/projects/[projectSlug]/[stage]">> = Specific
  const handler = {} as typeof import("../../app/w/[workspaceSlug]/projects/[projectSlug]/[stage]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[workspaceSlug]/projects/[projectSlug]/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceSlug]/projects/[projectSlug]/overview">> = Specific
  const handler = {} as typeof import("../../app/w/[workspaceSlug]/projects/[projectSlug]/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[workspaceSlug]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceSlug]/settings">> = Specific
  const handler = {} as typeof import("../../app/w/[workspaceSlug]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workspaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces">> = Specific
  const handler = {} as typeof import("../../app/workspaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sign-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sign-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sign-up/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-up">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sign-up/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/files/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/files/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trpc/[trpc]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trpc/[trpc]">> = Specific
  const handler = {} as typeof import("../../app/api/trpc/[trpc]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[workspaceSlug]/projects/[projectSlug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/w/[workspaceSlug]/projects/[projectSlug]">> = Specific
  const handler = {} as typeof import("../../app/w/[workspaceSlug]/projects/[projectSlug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
